pipeline{
    agent {
        node {
            label 'gs_agent'
        }
    }
        parameters {
        string(name: 'PERSON', defaultValue: 'Mr FUCKER', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
            stages {
        stage ('BUILD'){
            steps {
                echo "building.."
            }
        }
         stage ('TEST monkey'){
            steps {
                echo "testing.."
             }
        }
         stage ('DEPLOY FUCK'){
            steps {
               echo "deploying.."
            }
        }
        stage('fUCK PARAM') {
            steps {
                echo "Hello ${params.PERSON}"

                echo "Biography: ${params.BIOGRAPHY}"

                echo "Toggle: ${params.TOGGLE}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
            }
    }
}
}