pipeline{
    agent{
        node {
            label 'gs_agent'
        }
    }
    stages {
        stage( 'INIT')
            steps {
                sh """
                terraform init
                """
            }

        }
        stage('PLAN')
            step {
                sh """
                terraform plan
                """
            }
 }

